### ISSUE TITLE
FYI. . .

### ISSUE THREAD

**Issue by ogrotten** [alaingalvan/webgl-seed#1]
https://old.reddit.com/r/javascript/comments/egpxxe/raw_webgl_by_alain_galvan/

Thought you might want to know that there are problems with the repo.

Even the last link in the article, linking to the repo, is spelled wrong.

Good Luck.

**Comment by alaingalvan** [comment]
Thanks **so much** for letting me know, I'm in the process of correcting all errata right now! 🔥🚒

EDIT: Thanks again, left this repo with stub code for a while, this was the kick I needed to get it all in. 

EDIT 2: Closing the issue since everything should be good now (added a CodePen and Travis build too for verification), I can reopen it if anything.
